#Name: Kevin Du
#Date: 11/14/20212
#ID: kd5eyn
#Filename: Makefile

CXX = clang++

CXXFLAGS = -Wall -g

AS = nasm

ASFLAGS = -f elf64 -g

OBJECTS = threexplusone.o threexinput.o

a.out: $(OBJECTS)
	$(CXX) $(CXXFLAGS) $(OBJECTS)


